apiVersion: 1

groups:
  - orgId: 1
    name: app-slo-rules
    folder: AWS Observability
    interval: 1m
    rules:
      - uid: app-error-rate-rule
        title: App high error rate
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus-central
            relativeTimeRange:
              from: 300
              to: 0
            model:
              editorMode: code
              expr: sum(rate(http_server_requests_total{status_code=~"5.."}[5m])) / clamp_min(sum(rate(http_server_requests_total[5m])), 1)
              instant: false
              intervalMs: 30000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              type: threshold
              conditions:
                - evaluator:
                    params: [0.05]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              refId: B
        noDataState: NoData
        execErrState: Error
        for: 10m
        annotations:
          runbook_url: https://example.local/runbooks/app-high-error-rate
        labels:
          severity: critical
          team: platform
          service: app
          namespace: application
          environment: dev
          cluster: shared

      - uid: blackbox-latency-rule
        title: Endpoint high latency
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus-central
            relativeTimeRange:
              from: 300
              to: 0
            model:
              editorMode: code
              expr: probe_duration_seconds{job="blackbox-http"}
              instant: false
              intervalMs: 30000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              type: threshold
              conditions:
                - evaluator:
                    params: [1.5]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              refId: B
        noDataState: NoData
        execErrState: Error
        for: 10m
        annotations:
          runbook_url: https://example.local/runbooks/blackbox-high-latency
        labels:
          severity: warning
          team: platform
          service: blackbox
          namespace: external
          environment: dev
          cluster: external
