apiVersion: 1

contactPoints:
  - orgId: 1
    name: cp-slack-critical
    receivers:
      - uid: slack-critical
        type: slack
        settings:
          recipient: '#observability-critical'
          url: ${SLACK_WEBHOOK_URL}
          title: '{{ template "default.title" . }}'
          text: '{{ template "default.message" . }}'

  - orgId: 1
    name: cp-email-warning
    receivers:
      - uid: email-warning
        type: email
        settings:
          addresses: ${ALERT_EMAIL_TO}
          subject: '[Grafana][Warning] {{ .CommonLabels.alertname }}'

  - orgId: 1
    name: cp-teams-info
    receivers:
      - uid: teams-info
        type: webhook
        settings:
          url: ${TEAMS_WEBHOOK_URL}
          httpMethod: POST
