apiVersion: 1

muteTimes:
  - orgId: 1
    name: weekend-maintenance
    time_intervals:
      - weekdays: [saturday, sunday]
        times:
          - start_time: '01:00'
            end_time: '05:00'
