global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: ${ENVIRONMENT}
    cluster: ${CLUSTER}
    team: ${TEAM}
    service: prometheus

rule_files:
  - /etc/prometheus/rules/*.yaml
  - /etc/prometheus/recording-rules/*.yaml

scrape_config_files:
  - /etc/prometheus/scrape-configs/*.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
