global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: dev
    cluster: local-lab
    team: platform
    service: prometheus

rule_files:
  - /etc/prometheus/rules/*.yaml
  - /etc/prometheus/recording-rules/*.yaml

scrape_config_files:
  - /etc/prometheus/scrape-configs/*.yaml

alerting:
  alertmanagers:
    - scheme: https
      tls_config:
        insecure_skip_verify: true
      basic_auth:
        username: alert_admin
        password: alert-admin-change-me
      static_configs:
        - targets:
            - alertmanager:9093
